### ISSUE TITLE
Astronauts survived KABOOM!

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#740] opened 2023-01-28 17:37 UTC
My boosted Titan lit up, then exploded:
![BlowUp](https://user-images.githubusercontent.com/3118014/215282190-4b21f37f-5c89-4853-8851-95db07a5aa40.png)
(ttbl_01.ogg)

But everyone survived, even though we never saw any indication of the escape system firing.  This might be related to #725.
![ExplosiononPad](https://user-images.githubusercontent.com/3118014/215282214-08ca0163-1e1f-45cf-9bc3-e16cd74e37cd.png)

**Comment by hweimer** [comment] 2023-01-29 20:31
Was this a minishuttle launch? Looks like MissionIdSequence 110AUR505 has the wrong video file listed, should probably by ppix_07 (same as the capsule launch). MissionIdSequence 110AUR500 appears to have the same issue.

**Comment by peyre** [comment] 2023-01-29 20:52
Yes, it was.  I flew XMS-2 again and experienced the same or a similar issue today as well.

I tend to flip through the missions, so this happened pretty fast.  I saw an unboosted Titan in the pad and thought "That's odd, the XMS-2 should need boosters."  But then "YOWW!!" when it exploded.  Then I got a message saying they were evacuated safely IIRC.

I'm not sure--I can't seem to make much of data_decoder.cpp, but wrong video files would explain the issue here.

**Comment by hweimer** [comment] 2023-01-29 21:30
The unboosted Titan was probably yet another incorrect video sequence. There are quite a few of them, but I haven't gotten around to address them because I hardly understand how the game selects the video files. On top of that, the funny binary format of fseq.dat doesn't really help either. Probably a good starting point to finally do something about #3.

**Comment by peyre** [comment] 2023-02-01 05:15
Oh yeah, I'd love to get a few of those very early Issues resolved.  Changing the binary files to plaintext would be very nice, among other things.

**Comment by peyre** [comment] 2023-02-04 18:20
I'm starting to run a series of XMS test launches, forcing failures to see what happens.  Here's one that I'm not sure if we consider it important.  The shuttle is atop a boosted Titan, but after "rolling" the failure, the game shows an unboosted Titan explode.

![TitanFail](https://user-images.githubusercontent.com/3118014/216783232-90037002-1dd8-4a58-b4f0-90284a03446d.png)

**Comment by peyre** [comment] 2023-02-04 18:35
This happened while I was testing.  During a dice = 98, it showed the following in the terminal:

Thread 1 "raceintospace" received signal SIGSEGV, Segmentation fault.
StepSafety (step=...) at /home/leon/raceintospace/src/game/mis_m.cpp:670
670	                  MH[1][Mission_Capsule]->MisSaf) / 2;

![SegFaultGame](https://user-images.githubusercontent.com/3118014/216783887-c0df8dea-e8a1-4dd5-b61d-f8b394ca797f.png)

**Comment by hweimer** [comment] 2023-02-05 06:17
Good catch! Do you remember which mission you were flying? I guess the step affected was the one after docking?

**Comment by hweimer** [comment] 2023-02-05 12:15
I think I got it, thanks to your detailed report. If you have a code 9 failure (FURTHER PROBLEMS: RECHECK) on launch, the inSpace global variable gets incremented twice, and the game thinks you are flying a mission with two capsules. If the mission has a duration step later on, the game crashes because there is no second capsule.

Let's hope that this takes care of the other segfaults that you were encountering as well. At least in one case, I remember you mentioning that the crash occurred during or after EVA, so that sounds consistent.

**Comment by peyre** [comment] 2023-02-05 16:25
A little late with this one, but the mission was an Orbital Docking Duration (D).

That's great Hendrik!  I'm glad you were able to track it down so fast.

And my son got some laughs out of my report!

**Comment by hweimer** [comment] 2023-02-14 22:20
I've started looking into the sequence selection code, but the problem is bigger than I initially thought. The storage of replays also needs to be updated as it uses the same indexing madness as the video and audio files. babypicx.cdr deals with the small images next to the video screen, I suppose? Let's hope that at least this stuff can remain untouched.

**Comment by peyre** [comment] 2023-02-15 16:35
Uh oh, that's too bad.  I had hoped this one would be pretty straightforward.  I do think it's important to address at some point, since - unlike, say, Lapot - there seems to be a fair number of RIS players who are big fans of the XMS-2.

**Comment by hweimer** [comment] 2023-02-18 08:21
I've managed to replace seq.dat and fseq.dat with JSON files. However, the replay code still needs to be addressed, and there are quite a few challenges:
1. Replay data is stored in save files. This means we can have the situation that part of the data was saved using the old format and the other part is in a new format. If we are lazy, we could simply ignore any replays in the old format, so you cannot watch them anymore in the space museum. Certainly not an optimal solution.
2. The old replay format assumes a data structure with fixed offsets (e.g., the animations showing a succesful Atlas launch have to start at the 109th entry in the file). One of the main motivations behind moving to JSON files is that we have flexibility to add new entries to the data structures.
3. Failure sequences are currently using two indices, one for the step, and one for the sequence number within a given step. This is somewhat tricky to work with using JSON vectors (you have to be careful with the brackets), so I have decided to flatten this to one index, like in the case of successful sequences (which also simplifies the code quite a bit). But this is also at odds with the old replay code.

**Comment by peyre** [comment] 2023-02-18 19:07
Ugh, complications.  I'm usually big on backward compatibility, but I've never considered it important in RIS; we don't have a large number of players and save games aren't really important.  Games of RIS are fairly short and it's always easy to start another one.  So as far as I'm concerned, we can ignore backwards compatibility on this if that's a complication.

**Comment by hweimer** [comment] 2023-02-20 20:34
I think backwards compatibility is doable if we provide a mapping from the old offsets to the sequence names like 750AUR125, which is what the new code uses as an identfier. Autogenerating this mapping should not be too hard. So once we encounter a save game in the old format, we can convert the replay data to the new format already during loading of the file.

(If we do it like that, then fixing bugs with the sequences like the ones you mentioned here would even fix the old replays.)

**Comment by peyre** [comment] 2023-02-20 23:00
I have no problem with that.  Is it something you can implement?

**Comment by hweimer** [comment] 2023-02-21 07:28
I hope so, shouldn't be too difficult.

**Closed** 2023-03-05 23:42 UTC
Labels: bug
