### ISSUE TITLE
Mission penalty popup

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#168] opened 2018-06-16 16:17 UTC
One nice extra we could add would be in Future Missions: the button that says A-OK!, CAUTION!, or DANGER!.  If it's -1 or below, clicking on it could bring up a popup window showing what penalties the mission faces. So for instance if you were scheduling a manned suborbital without having flown the satellite, it could show something like:
MILESTONE PENALTIES
-1 NEW MISSION TYPE
-3 ORBITAL SATELLITE

**Comment by peyre** [comment] 2020-07-12 00:17
I've successfully added one to Future Missions, though it could use some fine-tuning.  I should also add a line for LM penalty, where appropriate, for #373.

And maybe I could do this again somewhere in Mission Control, too.

**Comment by peyre** [comment] 2020-07-12 17:44
This morning I added a line for "PENALTY ON LM STEPS" which appears only on Historical, LOR, and EOR lunar landing missions.

I would close this one, except I think it would be good to add something like this to Mission Control.

**Comment by rnyoakum** [comment] 2020-07-13 01:16
I made some modifications to the popup code, mostly behind the scenes, but I also gave it its own control loop so it could be closed without having the change the mission selection. Before closing this issue, I wonder if it would be helpful to color-code the individual penalty listings, like the way the mini-display colors the penalty?

**Comment by peyre** [comment] 2020-07-13 18:42
Thanks, Ryan!  I appreciate you cleaning up after me like this - when I make a significant change to the code it's usually pretty ugly since I don't really know what I'm doing.  I was going to ask if you could make it so you can close the window by clicking the CONTINUE button, but you've already done it, very nice!  Do you think we could add something like this to Mission Control as well?

**Comment by rnyoakum** [comment] 2020-07-13 19:39
Yeah, something similar to this could be added to mission control, if you have in mind a good place to launch it from. While the FM screen has the penalty display panel, the Mission Control screen has a line of text which doesn't suggest it's able to interact. The whole line _could_ be turned into a button, but a button requires more margin than I think it available.

**Comment by peyre** [comment] 2020-07-13 19:58
I've thought about that too.  Maybe we could add a little button somewhere?  Granted there isn't much room; this screen is getting kind of busy.

![Mission Control](https://user-images.githubusercontent.com/3118014/87347711-86312780-c508-11ea-8836-4d6d81c9076c.png)

**Comment by rnyoakum** [comment] 2020-07-13 21:12
My concern with a button like that is that there is no visual context to suggest what it does, and RIS is the sort of game which needs a straightforward, intuitive interface. That's actually a problem in the FM screen; how do you know to click on the penalty display? Here, there's nothing to explain it. Now, perhaps the answer to the problem is "curiosity," but I think it deserves a better design.

This next part is just me brainstorming:
- The launch pad image could serve as a button, but there would need to be some visual clue to recommend it, and it would have to be subtle - I like the current look and don't want to disturb it.
- I have an idea of how to code a tool tip for when the player hovers over an area, but that's a departure from the traditional RIS style, and I'd have to test it to gauge the visual performance.
- The requirement penalties and rushing penalty were originally put on separate lines to distinguish between the two, but if there's a popup explaining the source of the penalties, would that justify combining the two (and freeing up some space)?

**Comment by peyre** [comment] 2020-07-13 22:02
I agree; having a button that doesn't indicate what it does is less than ideal.

If we were to do something in the launch pad screen, I suppose we could split the SCRUB MISSION button in half and place a PENALTIES button next to it.  I agree with not changing the look of the pad image.

A tooltip is a good idea--if, as you say--you're able to get it working.

I kind of like the idea of leaving rushing separately from requirement penalties; as it is, the game makes it obvious that rushing a mission costs extra and adds a penalty.  What about using the image of the pad in Mission Schedule as a (rather large) button that brings up a pop-up?

**Comment by peyre** [comment] 2020-07-14 17:25
It would also be good if we could somehow make the penalty popup look more like a button - maybe have it be just the penalty number box (so clicking on A-OK / WARNING / DANGER wouldn't do anything) and animate the button when it's pressed?

**Comment by peyre** [comment] 2020-07-16 18:10
Well, now I've gone and eliminated that precedent for hidden buttons, by making the flag in Hardware Efficiency / Prestige Points look and act (partly?) like a button instead of just a decoration like in other screens.

**Comment by peyre** [comment] 2020-07-25 18:32
I've modified Future Missions - now the A-OK/WARNING/DANGER area doesn't respond, and the box showing mission penalties now acts like a button.  I also made CONTINUE in the pop-up button much bigger (feel free to change it if you think it doesn't look right).

![FutureMissionsPenalties](https://user-images.githubusercontent.com/3118014/88463812-74d20e80-ce6a-11ea-8501-bd620a7700e5.png)

**Comment by peyre** [comment] 2020-08-08 19:37
I'm working on adding this to Mission Control.  I've managed to get the launchpad images to work as buttons without changing how they look, but I'm having difficulty getting the penalty pop-up working.

**Comment by peyre** [comment] 2020-08-09 17:32
Ok, I've added a penalty pop-up to Mission Control!  This implements Ryan's first idea: the launch pad images now act as buttons that bring up the pop-up.

![MissionControl](https://user-images.githubusercontent.com/3118014/89738153-59026700-da2b-11ea-932f-0031ae4db0c4.png)

**Closed** 2020-08-30 01:28 UTC
Labels: Enhancement

**Comment by peyre** [comment] 2020-08-30 03:18
Thanks so much for taking care of that, Ryan.
