### ISSUE TITLE
LM failure kills wrong crew members

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#476] opened 2020-09-27 17:56 UTC
On an Apollo Historical Lunar Landing, something went catastrophically wrong with my LM and those aboard were killed.  The game killed the LM Pilot and Docking Specialist, leaving the Command Pilot alive.  I didn't think anything of it until after the landing, when it then asked who should get out first!  Shouldn't it be the Docking Specialist who stays with the capsule?

![Dead walks on Moon](https://user-images.githubusercontent.com/3118014/94372120-08fd6380-00b0-11eb-8ccf-6a4a4002401d.png)

**Comment by rnyoakum** [comment] 2020-09-28 20:33
Do you remember what the failure was, or on which step?

**Comment by peyre** [comment] 2020-09-28 20:41
Not specifically.  It was early into the LM part of the mission though, perhaps Lunar De-Orbit Burn.

**Comment by rnyoakum** [comment] 2020-09-29 01:02
There are two issues here, I) who is supposed to land on the moon, and II) why didn't the mission branch properly?

I) Who's gonna to fly it, kid? You?
The first is kind of tricky, because of how RIS handles skills - each crew member is fully responsible for an aspect of the capsule. Per the Capsule buildings, the skill breakdowns among the crew are:

0. Capsule specialist
1. EVA & LM specialist
2. Docking specialist

This feels a little weird when trying to map this onto historical missions; I'll use Apollo 11 as an example. Historically, Armstrong was the Commander, Collins the Capsule Module Pilot, and Aldrin the Lunar Module Pilot. The following is my guess at how this translates into crew roles in the game, relying on [Wikipedia](https://en.wikipedia.org/wiki/Astronaut_ranks_and_positions):

I'd expect Collins to be in charge of Docking because the CM pilot was responsible for docking when the LM returned from the lunar surface. He was also (per Wikipedia) historically responsible for navigating during trans-lunar & trans-earth stages, which are CA tests but arguably should fall under the Docking skill (see https://github.com/raceintospace/raceintospace/issues/384#issuecomment-671569498 for @peyre's relevant comment about this). That would make Armstrong the Capsule specialist, appropriate to his CA rating, which leaves Aldrin the LM/EVA roles. This is slightly awkward since Armstrong manually piloted the LM historically while Aldrin would be making the LM test in-game, but I think it's still the best mapping.

_Side note: There's also an exception to distribution of roles listed in the capsule/shuttle buildings. For a 3-person crew using a 2-person Lunar Module, the EVA role is assigned to the Docking specialist. That's about to be relevant._

When your mission step failed (probably during Lunar De-Orbit Burn) it produced a Code 31 error. That's supposed to kill the LM crew and branch the mission. The failure code interprets the LM crew as the EVA and the LM specialists. From your comments, this worked as intended. The mission branching didn't, but that's beyond the scope of this problem.

However, the lunar landing code works a differently. It checks how many astronauts are landing on the moon: 4 for Direct Ascent, 3 for Soyuz LL, 2 for Eagle/LKM, 1 for Cricket/LK. If only one astronaut is landing, it chooses the second astronaut on the crew; that should be the LM/EVA specialist. Otherwise, RIS offers a selection of X many astronauts, _starting from the first slot_. For a two-person LM, that means the capsule specialist and the EVA/LM specialist.

So who's supposed to be in the LM? The First Man code suggests Capsule and EVA/LM specialists, which feels like a better historical fit. The LM failure code uses the LM & EVA(/Docking) specialists, which makes sense because the capsule **is** flown home using the Capsule specialist's CA skill bonus (I'm unsure right now how hard that would be to change).

So who's gonna fly it, Leon?

II) Why didn't the mission branch properly?
When the mission encounters a failure state where everyone on that part of the mission (the LM crew, half of a joint launch, or everybody) is killed, it's supposed to branch to the AltD path. For the LM steps on a Lunar Landing, that's supposed to be Step 15: Trans-Earth Injection (steps are indexed from 0). The failure code told the mission to branch to the AltD step, so... I'm still figuring this part out.

**Comment by peyre** [comment] 2020-09-29 04:44
These are _very_ good questions.  It seems to me that with the 2-seat LM, ideally speaking, it should be the Command Pilot and LM Pilot who go down to the surface while the Docking Specialist (CMP, Collins), and if there's a Lunar Orbital Activities step for the time he spends alone (I assume there is, but haven't checked), it should be rolled against his DO skill.  The reason for that is 1) it's what you're led to expect that crew member to need, and 2) after all, he's not piloting the craft, but handling shipboard activities--could be handled by any skill.

So I would think that the CP and LMP should have been killed in this scenario and the CMP survived (and, of course, the landing would be canceled).  As it was, the button for Borman was deactivated, so the game at least prevented me having the Zombie Borman walk on the Moon.  But the landing proceeded once I selected Powell.

That's a really good point about what happens now with Collins coming home alone.  The mission now has no one left dedicated to CA skill.  I'm not sure how that's handled in the code, so I don't have a good handle on what our realistic are, realistically.  Perhaps on a mission that's suffered a crew death that eliminates the dedicated crew member, the astronaut with highest CA takes over as backup?  I don't know if that's doable.

**Comment by peyre** [comment] 2020-10-18 20:58
Progress!  I see that now, an LM catastrophe kills the Commander and LM Pilot, but it doesn't prevent the mission continuing(!)

![dead](https://user-images.githubusercontent.com/3118014/96385637-068ba800-114a-11eb-9cc5-c8887b99ec60.png)

**Comment by rnyoakum** [comment] 2020-10-20 05:50
Do you remember the failure message for this latest test? I've been trying to recreate this problem, but in my play-through after killing off the LM crew the mission successfully skips the remaining LM steps and proceeds to Trans-Earth Injection.

So I'm wondering if you're dealing with a different error code? I've been forcing an Code 31 error
```
ENGINE EXPLODES UPON IGNITION. SPACECRAFT CREW IS KILLED.
```
on step 7 (0-indexed), the Lunar De-Orbit Burn. For me, that's now working correctly, and I assumed that was the problem you were having from your description. But maybe you're encountering something else?

**Comment by peyre** [comment] 2020-10-20 15:04
Huh!  I wish I'd screenshotted the Step Failure screen when I had the chance.  I guess I'll have to test some more to try to get an LM failure.

**Comment by peyre** [comment] 2020-10-20 15:11
On a bit of a side note, I wonder if it would be a good idea to add an option to cancel the landing.  This screen could display the EVA Safety, for instance, and if the EVA safety was downgraded by a newscast or catastrophic failure and the player forgot about it (which I've done a few times) they'd have an option to abort the EVA.

**Comment by rnyoakum** [comment] 2020-10-20 15:51
> Pretty sure it happened after the Lunar Recon step, but what the failure was exactly, I don't recall.

That's still useful - between Lunar Recon and before Lunar EVA.

> On a bit of a side note, I wonder if it would be a good idea to add an option to cancel the landing. This screen could display the EVA Safety, for instance, and if the EVA safety was downgraded by a newscast or catastrophic failure and the player forgot about it (which I've done a few times) they'd have an option to abort the EVA.

I don't think the American taxpayers spent 50 million dollars to take you to the swimming pool only for you to be afraid to get your feet wet. From a historical perspective it doesn't feel realistic that a mission would go that far and then get called off based on facts already known beforehand.

What might be a good compromise is adding EVA suits (perhaps even Photo Recon) to the pre-flight mission announcement (aka the last chance to scrub the mission) when relevant.

**Comment by peyre** [comment] 2020-10-20 15:56
X-)  Ha, nicely put!  (Actually this wouldn't even have occurred to me, I think, if I hadn't been stuck at this screen, so the EVA skittishness idea was sort of an after-the-fact rationalization.)

That's a good idea!  In fact, it would make sense for EVA Safety to show for any mission that included EVA.

**Comment by rnyoakum** [comment] 2020-10-22 00:12
> What might be a good compromise is adding EVA suits (perhaps even Photo Recon) to the pre-flight mission announcement (aka the last chance to scrub the mission) when relevant.

I added the EVA component with commit 16e78a9.

**Comment by peyre** [comment] 2020-10-24 15:50
Hm, here's one, might be a separate issue.

![LM Explodes](https://user-images.githubusercontent.com/3118014/97086053-e5a5d580-15d5-11eb-8b4c-ea836019b9f2.png)
![Craft continues](https://user-images.githubusercontent.com/3118014/97086054-e8a0c600-15d5-11eb-8b14-58a440e8bb3c.png)
![alldead](https://user-images.githubusercontent.com/3118014/97086057-ea6a8980-15d5-11eb-97e6-22e7e43105a1.png)

**Comment by peyre** [comment] 2020-10-24 16:21
Ok, it took a few tries, but I got it.  Here's the failure code etc.

![lem](https://user-images.githubusercontent.com/3118014/97086786-4e8f4c80-15da-11eb-8696-f95fbf9f99c9.png)
![lm trouble](https://user-images.githubusercontent.com/3118014/97086787-4f27e300-15da-11eb-9119-bd7f6ab0e9a9.png)
![everyone dead](https://user-images.githubusercontent.com/3118014/97086788-4fc07980-15da-11eb-806e-9873f1a8f192.png)

**Comment by rnyoakum** [comment] 2020-10-24 21:51
So, I can explain the [first of your comments](https://github.com/raceintospace/raceintospace/issues/476#issuecomment-715950254) from today. The LM explosion **should** kill the LM crew and not the whole flight crew, but the same error I explained [here](https://github.com/raceintospace/raceintospace/issues/287#issuecomment-716059543) is happening in this case as well; the wrong error set is being used, specifically the De-Orbit Burn errors for Soyuz / Direct Ascent. That error set, understandably, kills the entire flight crew when a Catastrophic Error is achieved.

The mission continues, as you note, but it does not continue to a lunar landing; the next step is Trans-Earth Injection. That's as it should be. If the correct error set had been used, the LM crew would be dead and the Command Module Pilot would proceed with Trans-Earth Injection to return home.

**Comment by peyre** [comment] 2020-10-25 16:43
Good work Ryan, thanks!  I'm glad to see us fixing some of these abnormalities in failure handling.

**Comment by peyre** [comment] 2021-01-12 05:56
I encountered this again tonight.  This one was weird: a failure killed Dwight and injured the other two crew members, but the lunar landing was attempted anyway.  Then another failure killed the LM Pilot, and I'm stuck at the "Who should get out first" screen and there's nothing I can do to get past this.  Maybe there should be an option to abort the mission at this point?  That would allow players to get past this impasse without having to X out of the game.

![Both Dead](https://user-images.githubusercontent.com/3118014/104275345-84b0cf80-5457-11eb-970e-2e8820a10b6e.png)

**Comment by peyre** [comment] 2021-01-18 17:59
I think we have a related issue, with single-seat landers.  This was on a Jt Lunar Landing EOR with Gemini.  Cernan is the LM Pilot, all right, but the game doesn't kill him when it says it does.  It did have the capsule return home without any lunar EVA being performed, but Cernan must've beamed back up to it! ;)

![Crew killed or not 1](https://user-images.githubusercontent.com/3118014/104949316-9cb2b280-5973-11eb-8196-709f6fa4c178.png)
![Crew killed or not 2](https://user-images.githubusercontent.com/3118014/104949319-9d4b4900-5973-11eb-8d72-0aab52be81a1.png)
![Crew killed or not 3](https://user-images.githubusercontent.com/3118014/104949321-9d4b4900-5973-11eb-9578-2fea26c26f57.png)

**Comment by peyre** [comment] 2021-04-21 23:54
Again I wish I'd screenshotted it, but I think the error with this one was ENGINES, ENGINE THROTTLE FAILURE CAUSES EXPLOSION. FLIGHT CREW KILLED.  That was during LEM Activities, so the next screen showed everyone dead and the only thing I could do was X out of the game.

![All dead on Moon](https://user-images.githubusercontent.com/3118014/115636221-4b8fc300-a2c2-11eb-96f0-e0aef6c8d531.png)

**Comment by hweimer** [comment] 2021-04-22 20:54
In case you encounter this bug again, can you post the Mev information for the step that killed the nauts (i.e., calling "print Mev[10]" in gdb)? I have created PR #531 to make it convenient to run the game in the debugger by simply running "make gdb" in the build directory.

**Comment by hweimer** [comment] 2021-04-27 21:45
Got it! The problem is that the dialog is presented _before_ the STEP counter advances to the actual lunar EVA. The reason for this is that the previous step (LEM activities) contains the information about the hardware used (LM or capsule), which is required to figure out how many people are actually on the lunar surface. However, the code didn't check whether the previous step was successful, so even a catastrophic failure during LEM activities would show the dialog.

**Closed** 2021-04-27 21:58 UTC
Labels: bug
