### ISSUE TITLE
End Screen - Text formatting and Game crash

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#208] opened 2019-01-01 19:40 UTC
I just completed a game (which I lost by a hair) and found the text wasn't formatted right.  That may be my doing; I edited the files for those not too long ago.  I'll have to have a look at them.

![gameending](https://user-images.githubusercontent.com/3118014/50575812-f7433b00-0db9-11e9-8e41-a7a23b40c43a.png)

Then when I hit Continue, the game crashed.  I don't know if this is related or not.  It gave the following: 
raceintospace/src/display/legacy_surface.cpp:142: void display::LegacySurface::checkPaletteCompatibility(display::LegacySurface*): Assertion `myColor.rgba() == otherColor.rgba()' failed.
Aborted (core dumped)

**Comment by peyre** [comment] 2019-01-01 22:37
I've uploaded an updated endgame.dat that seems to fix the text issue, but the game continues to crash.  The end page opens and the flag or Lenin fades in, but then it crashes immediately.

**Comment by pemensik** [comment] 2019-08-21 09:26
@peyre I cannot find attached endgame.dat file. I may help with fixing assertion failure, if you provide save game required.

**Comment by peyre** [comment] 2019-08-25 16:50
Sorry for the delay, Petr.  I reinstalled my OS from scratch recently, and lost my save games.  I've recompiled from the latest source and run a game, which, yes, crashed at the end (at least it's consistent).  Here's the endgame.dat from it.  (It looks like GitHub doesn't support .dat files, so it probably didn't aceept it before and I didn't notice.  So I've zipped it up here.)
[endgame.dat.zip](https://github.com/raceintospace/raceintospace/files/3538384/endgame.dat.zip)

**Comment by pemensik** [comment] 2019-09-07 21:31
Oh, I wanted more some game save before win. Well, I played a bit with it. I made extremely bad game progress, but I have now way to reproduce crash on the end of game (I lost so much ...) That was the first time I finished that game anyway.

[lost.zip](https://github.com/raceintospace/raceintospace/files/3587048/lost.zip)

```
(gdb) bt
#0  0x00007ffff75e557f in raise () from /lib64/libc.so.6
#1  0x00007ffff75cf895 in abort () from /lib64/libc.so.6
#2  0x00007ffff75cf769 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007ffff75dda26 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000004a6eb3 in display::LegacySurface::checkPaletteCompatibility (
    this=0x7fffe000bdc0, other=<optimized out>)
    at /usr/src/debug/raceintospace-1.1.0-1.20190907git0a422b5.fc29.x86_64/src/display/legacy_surface.cpp:142
#5  0x00000000004a6ef7 in display::LegacySurface::copyFrom (
    this=0x7fffe000bdc0, surface=0x7fffe000a990, x1=0, y1=0, x2=319, y2=199)
    at /usr/src/debug/raceintospace-1.1.0-1.20190907git0a422b5.fc29.x86_64/src/display/legacy_surface.cpp:159
#6  0x000000000043ece3 in Burst (win=1 '\001')
    at /usr/src/debug/raceintospace-1.1.0-1.20190907git0a422b5.fc29.x86_64/src/game/endgame.cpp:95
#7  0x0000000000440738 in NewEnd (win=1 '\001', loc=0 '\000')
    at /usr/src/debug/raceintospace-1.1.0-1.20190907git0a422b5.fc29.x86_64/src/game/endgame.cpp:543
#8  0x00000000004565e7 in MainLoop ()
    at /usr/src/debug/raceintospace-1.1.0-1.20190907git0a422b5.fc29.x86_64/src/game/game_main.cpp:626
#9  0x000000000045570b in game_main_impl (argc=<optimized out>, 
    argv=<optimized out>)
    at /usr/src/debug/raceintospace-1.1.0-1.20190907git0a422b5.fc29.x86_64/src/game/game_main.cpp:311
#10 0x000000000045663a in game_main (argc=2, argv=0x7fffffffc540)
    at /usr/src/debug/raceintospace-1.1.0-1.20190907git0a422b5.fc29.x86_64/src/game/game_main.cpp:347
#11 0x00007ffff75d1413 in __libc_start_main () from /lib64/libc.so.6
#12 0x000000000041911e in _start ()

(gdb) frame 4
#4  0x00000000004a6eb3 in display::LegacySurface::checkPaletteCompatibility (
    this=0x7fffe000bdc0, other=<optimized out>)
    at /usr/src/debug/raceintospace-1.1.0-1.20190907git0a422b5.fc29.x86_64/src/display/legacy_surface.cpp:142
142	            assert(myColor.rgba() == otherColor.rgba());
(gdb) p myColor 
$1 = {r = 240 '\360', g = 240 '\360', b = 240 '\360', a = 0 '\000'}
(gdb) p otherColor
$2 = {r = 236 '\354', g = 236 '\354', b = 236 '\354', a = 0 '\000'}
```

**Comment by peyre** [comment] 2019-09-07 22:10
Huh!  So, any idea how to fix it?

**Comment by pemensik** [comment] 2019-09-07 22:44
Actually, yes, I think I found it! Though I have to admit, game code is terrible on some places, including final screen. Pushed fix to my repo, along with change to compile under clang. Which on my Fedora works well, unlike gcc.

**Comment by peyre** [comment] 2019-09-10 16:06
I think we can consider this one fixed, unless you think otherwise, Petr.  Let me know.

**Comment by rnyoakum** [comment] 2019-09-10 19:23
Nice catch - I had assumed there was a palette mismatch between the rest of the display and an image being loaded, but from your commit it looks like it was just vhptr needing to be cleared. I tested the commit on my machine using the save file you provided - I've didn't have any saves near the end of the game - and it appears to work.

**Closed by rnyoakum** 2019-09-10 19:23 UTC
Labels: bug
