### ISSUE TITLE
Maximum R&D not affected when safety level increased by event

### ISSUE THREAD

**Issue by mackensen** [raceintospace/raceintospace#146] opened 2017-10-01 21:16 UTC
I saw this sequence of events with the Atlas:

- I had researched up to a safety level was at 75%
- An event at the start of the turn informed me that the safety level had been increased by 17 points
- The safety level of the Atlas was now at 92%; the maximum R&D was still at 87%

I would have expected that the maximum R&R would be increased to 92%. That season I flew a successful mission with the Atlas. The maximum R&D is now 88%; the safety factor is 93%.

**Comment by peyre** [comment] 2018-06-01 22:13
Sounds like newscasts aren't upgrading the Max R&D to match the Max Safety.

**Comment by rnyoakum** [comment] 2019-10-28 19:11
The newscasts aren't upgrading the Max R&D. There are two types of events that cause increases in a program's R&D

- Stealing technology from an opposing player (Events 5 & 47)
- Scientific breakthroughs (Events 22, 23, 24, 84, & 94)

If either of these should increase the safety level beyond the Max R&D level, should it

1. Increase the Max R&D to match, up to the program's Maximum Safety, or
2. Cap the safety increase at the Max R&D level, or
3. Increase the safety up to the Max Safety, but do not increase Max R&D (current behavior)

Looking for a ruling here, @peyre.

**Comment by peyre** [comment] 2019-10-28 20:05
So, the message "A breakthrough in computer automation has led to increased reliability of the space agency's remote probes and satellites. The max R&D and max safety ... will be raised 5% each" is raising the Max Safety but not the Max R&D?  Seems to me it should do just what it says; that's clearly the intent of the developers.

**Comment by rnyoakum** [comment] 2019-10-28 20:37
Not quite. Event 21

> A BREAKTHROUGH IN COMPUTER AUTOMATION HAS LED TO INCREASED RELIABILITY OF THE SPACE AGENCY'S REMOTE PROBES AND SATELLITES. THE MAX R&D AND MAX SAFETY FACTOR OF THIS HARDWARE WILL BE RAISED BY 5% EACH.

does exactly that. It has no impact on the current safety value of any program. The events mentioned by mackensen (Events 22, 23, 24, 84, & 94) are variations on

> THERE HAS BEEN A SCIENTIFIC BREAKTHROUGH IN THE e PROGRAM. THE SAFETY FACTOR HAS BEEN INCREASED BY i%.

Now, they increase the current safety by some percent up to the Max Safety value of the hardware. However, at this moment they do not increase the Max R&D, so the result can be a current safety value > the Max R&D.

**Comment by peyre** [comment] 2019-10-28 20:48
Oh, I see.  I've always thought the way it worked was fine.  The Safety goes up x% due to a fortunate circumstance (up to Max Safety) without changing Max R&D; that kind of made sense to me.  Max R&D didn't change in the original game; Nicolas added it for me in RIS 1.0, I think, so that if your hardware was downgraded by a newscast, you could research back to where you left off; you didn't lose your hard-won Safety points because of a random event.

**Comment by rnyoakum** [comment] 2019-10-28 21:04
No opinion here. I can see the virtue of any of the three: 

1. Increase the Max R&D to match, up to the program's Maximum Safety, or
2. Cap the safety increase at the Max R&D level, or
3. Increase the safety up to the Max Safety, but do not increase Max R&D (current behavior)

For the first case, the player is performing R&D, so the max R&D should match the expanded understanding following the breakthrough. In the second, the player is performing great R&D so it should be capped, because that's as far as R&D can take them without field testing. For the third case, it's a scientific gift - this approach works, but we haven't mastered exactly why. I don't think any of the effects are too powerful / limited for an event card, so \*\*shrugs\*\*?

If options (1) or (2), I'll implement the system that way. If you decide on option (3), I'll close this issue per your official ruling that the RIS behavior is as expected.

**Comment by peyre** [comment] 2019-10-28 21:25
All things being equal, I think I'd leave it at 3.  I think of this newscast as a sort of "happy accident" outside the main thrust of the R&D process, if you take my meaning.  I don't have strong feelings about it (except I would not want to go with 2, because I think it's a nice bonus that this can raise you above Max R&D), but my inclination is to go with 3.

**Comment by rnyoakum** [comment] 2019-10-28 21:34
Okay. Then these event cards are working as designed, and the behavior is to expectations.

**Closed by rnyoakum** 2019-10-28 21:34 UTC
