### ISSUE TITLE
Number of DMs stuck

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#319] opened 2020-01-19 00:07 UTC
Funny, I just played a game where I don't think I paid for a docking module after prototyping it.  I didn't even notice until I scheduled an unmanned orbital docking followed by a manned docking (Orbit), and I saw the cost was the same for both.

It looks like somehow the number of DMs got stuck at 2 somehow, and it just stayed there, no many how many docking missions I flew.

![ExtraDMs](https://user-images.githubusercontent.com/3118014/72672287-8f838080-3a0c-11ea-8966-0027f1c37864.png)

**Comment by peyre** [comment] 2020-01-19 00:07
I do have a save game from this part of the game, if anyone wants it for research.

**Comment by rnyoakum** [comment] 2020-01-20 03:55
Sure, I'd be interested in checking this out if you'd like to email me the save.

**Comment by peyre** [comment] 2020-01-20 17:50
Sounds good.  (You've asked about savegames before with other issues, and I wanted to make sure I had one for you this time if you wanted it.)  I don't consider this a huge bug; it seems to be pretty rare...but if you find it without too much trouble, so much the better. :)

    On Sunday, January 19, 2020, 7:55:36 PM PST, Ryan Yoakum <notifications@github.com> wrote:  
 
 
Sure, I'd be interested in checking this out if you'd like to email me the save.

**Comment by peyre** [comment] 2020-03-17 15:00
Ok, I just had it happen and was paying closer attention this time.  It happened the turn after I flew two Unmanned Orbital Docking missions on Pads A and B.  Both attempts were made (that is, they made orbit and tried to dock), but failed, so I gained a total of 10% Safety.  

Maybe buying two DMs in one turn gets it stuck, or maybe buying DMs for two Unmanned Orbital Docking missions in one turn does it.  I'll have to keep an eye on this one.

**Comment by peyre** [comment] 2020-06-27 22:38
Just a further clarification: it happens before you assemble them, so it occurs prior to you buying anything.

**Comment by rnyoakum** [comment] 2020-07-07 23:14
I think I know what's going on here, and it's tied into #309.

In src/game/mc2.cpp, `void MissionSetup(plr, mis)`:
```
 673         if ((Mis.mVab[j] & 0x10) > 0 && Data->P[plr].DockingModuleInOrbit >      0) { // DMO
 674             Data->P[plr].Mission[mis + j].Hard[Mission_Probe_DM] = 4;
 675             DMFake = 1;
 676         }
```
Having a Docking Module in orbit, along with a variety of reasons (not shown) such as using a three-person capsule with your LM, adds a phantom docking module to the mission hardware. This allows the mission code to proceed with docking steps even though a DM wasn't included on the launch vehicle. It also sets the DMFake flag, so the phantom DM won't be removed from the player's DM supply.

Thus, later in `MissionSetup()` when it comes time to consume the hardware launched, DMFake determines whether or not the supply of DMs is decremented:

```
 730                 case Mission_Probe_DM:           // Secondary Equipment
 731                     if (t != 4) {
 732                         MH[j][i] = &Data->P[plr].Probe[t];
 733                         MH[j][i]->Used++;
 734 
 735                         if (Data->P[plr].Probe[t].Num > 0) {
 736                             Data->P[plr].Probe[t].Num -= 1;
 737                         }
 738                     } else {
 739                         MH[j][i] = &Data->P[plr].Misc[MISC_HW_DOCKING_MODULE];
 740 
 741                         if (DMFake == 0) {
 742                             if (MH[j][i]->Num > 0) {
 743                                 MH[j][i]->Num--;
 744                             }
 745 
 746                             MH[j][i]->Used++;
 747                         }
 748                     }
 749 
 750                     break;
```
It's critical not to decrement a DM if the DM's presence is being faked - for example, an Apollo capsule in a LM test - but as written this means the DM supply will not decrease while there's a DockingModuleInOrbit. Even then, as seen in https://github.com/raceintospace/raceintospace/issues/309#issuecomment-655074961, a successful docking test resets the DockingModuleInOrbit counter - and doesn't check DMFake to see if the docking module is a real or phantom DM.

I'm guessing that's the cause of this issue. Fortunately, the logic of what needs to be checked & when is pretty straightforward.

**Comment by peyre** [comment] 2020-07-07 23:26
Wow, I'm glad you're able to make sense of this...

**Comment by rnyoakum** [comment] 2020-07-11 21:12
Okay, a mea culpa for my earlier post, where I blamed the wrong section of code: it's not the line
```
 673         if ((Mis.mVab[j] & 0x10) > 0 && Data->P[plr].DockingModuleInOrbit > 0) { // DMO
```
causing the problem. I'd misread the mVab code; line 673 seems to be working as it should.

The full section of relevant code is:

```
    for (j = 0; j < (1 + Data->P[plr].Mission[mis].Joint); j++) {

        if ((Mis.mVab[j] & 0x10) > 0 && Data->P[plr].DockingModuleInOrbit > 0) { // DMO
            Data->P[plr].Mission[mis + j].Hard[Mission_Probe_DM] = 4;
            DMFake = 1;
        }

        if (j == 0) { // Apollo (1)  + LM (1)
            if (Data->P[plr].Mission[mis].Hard[Mission_Capsule] == 2 && Data->P[plr].Mission[mis].Hard[Mission_LM] >= 0) {
                Data->P[plr].Mission[mis].Hard[Mission_Probe_DM] = 4;
                DMFake = 1;
            }
        }

        if (j == 1) { // Apollo (2)  + LM (1)
            if (Data->P[plr].Mission[mis + j].Hard[Mission_Capsule] == 2 && Data->P[plr].Mission[mis].Hard[Mission_LM] >= 0) {
                Data->P[plr].Mission[mis].Hard[Mission_Probe_DM] = 4;
                DMFake = 1;
            }
        }

        if (Data->P[plr].Mission[mis].MissionCode == Mission_Soyuz_LL) { // Soyuz Kicker-C
            Data->P[plr].Mission[mis].Hard[Mission_Probe_DM] = 4;
            DMFake = 1;
        }

        if (Data->P[plr].Mission[mis].Hard[Mission_Capsule] == 2) { // Apollo #1
            Data->P[plr].Mission[mis].Hard[Mission_Probe_DM] = 4;
            DMFake = 1;
        }
```

The first section, commented DMO, should only apply for missions where no docking module is supplied but docking is required (such as Orbitals). There are also checks to see if the mission has an Apollo capsule docking with a LM, because the Apollo capsule has LM docking capability (and the VAB shouldn't add a DM for Apollo/LM missions). There's a spoofed DM in the case of a Soyuz Kicker-C on the Soyuz Lunar Landing mission. These are all good.

The problem is the final section,
```
        if (Data->P[plr].Mission[mis].Hard[Mission_Capsule] == 2) { // Apollo #1
            Data->P[plr].Mission[mis].Hard[Mission_Probe_DM] = 4;
            DMFake = 1;
        }
```
which spoofs a DM if an Apollo capsule is used on the first launch of a mission (single or joint). Because it's asserting that a DM is being spoofed, the mission doesn't consume the DM.

**Comment by rnyoakum** [comment] 2020-07-14 00:15
I think I caught the error that was giving you problems, so I'm closing this issue. Re-open if it recurs.

**Closed by rnyoakum** 2020-07-14 00:15 UTC
Labels: bug
