### ISSUE TITLE
Highlight Endurance skills in crew selection

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#586] opened 2021-09-21 15:12 UTC
It occurred to me that - since Endurance now helps with Duration missions - it should be highlighted in crew selection when you're planning a mission.  I got it working on Saturday, so far so good.  Now it's further occurred that maybe it shouldn't be highlighted if `use_endurance 0` or `game_style 1` is set in the config file.

![Endurance](https://user-images.githubusercontent.com/3118014/134197024-1c65dff2-3553-4966-bd02-fba912d39aa9.png)

**Comment by peyre** [comment] 2021-09-25 15:31
Well, bollocks!  I've set line 716 in crew.cpp to try to check for those settings, but the game segfaults:
`if ((mType > 24 && mType < 32) || (mType == 33 || mType == 34 || mType == 35 || mType == 37 || mType == 40) && options.feat_use_endurance != 0 && options.feat_game_style != 1) {`

**Comment by rnyoakum** [comment] 2021-11-28 00:45
My guess is this was related to #520, so I may have [solved the problem](https://github.com/raceintospace/raceintospace/issues/520#issuecomment-980814070).

**Comment by peyre** [comment] 2021-11-28 01:26
Thanks!

**Comment by peyre** [comment] 2021-11-28 17:32
Hum!  Modifying line 716 as above makes the game error out during compilation.  Taking out options.feat_game_style lets it compile successfully, but then the game fails to run if I turn on feat_use_endurance.

`Segmentation fault (core dumped)
`

**Comment by rnyoakum** [comment] 2021-11-28 17:58
> Taking out options.feat_game_style lets it compile successfully, but then the game fails to run if I turn on feat_use_endurance

Just to be clear, is the segmentation fault being caused by setting the value in the config file, or from modifying the code in crew.cpp?

**Comment by peyre** [comment] 2021-11-28 21:42
Took me a while to get you the answer (we were getting a Christmas tree), but it looks like just uncommenting the line in the config file causes it to segfault during compile, even if you set it to 1.

**Comment by peyre** [comment] 2021-11-28 22:23
Wait, hang on.  I think I haven't updated my local copy of the code.  I'll get back to you.

**Comment by peyre** [comment] 2021-11-28 22:36
Ah yes, that did it, thanks.  Now I can get it to not highlight EN if use_endurance is 0, but not if game_style is 1.

`/home/leon/raceintospace/src/game/crew.cpp: In function ‘void FutAstList(char, char, int, int, int, int)’:
/home/leon/raceintospace/src/game/crew.cpp:721:169: error: ‘struct game_options’ has no member named ‘feat_game_style’
  721 | mType == 40)) && options.feat_use_endurance != 0 && options.feat_game_style != 1) {
      |                                                             ^~~~~~~~~~~~~~~

make[2]: *** [src/game/CMakeFiles/game_test.dir/build.make:297: src/game/CMakeFiles/game_test.dir/crew.cpp.o] Error 1
make[2]: Leaving directory '/home/leon/raceintospace-build'
make[1]: *** [CMakeFiles/Makefile2:422: src/game/CMakeFiles/game_test.dir/all] Error 2
make[1]: Leaving directory '/home/leon/raceintospace-build'
make: *** [Makefile:163: all] Error 2
`

**Comment by rnyoakum** [comment] 2021-11-28 22:39
> `if ((mType > 24 && mType < 32) || (mType == 33 || mType == 34 || mType == 35 || mType == 37 || mType == 40) && options.feat_use_endurance != 0 && options.feat_game_style != 1) {`

This line won't compile because there is no `options.feat_game_style`. Internally, the `game_style` config option corresponds to `options.classic`.

**Comment by rnyoakum** [comment] 2021-11-28 23:09
> Now I can get it to not highlight EN if use_endurance is 0, but not if game_style is 1.

Setting `game_style 1` enables classic mode, which didn't support Endurance, s using classic mode overrides the `use_endurance` config setting and sets `options.feat_use_endurance = 0;`. Consequently, you shouldn't check `options.feat_game_style` in the conditional statement; rely solely on `options.feat_use_endurance`.

**Comment by peyre** [comment] 2021-11-29 00:12
Yes, taking out the feat_game_style fixed the segfault, thanks.  I'd wondered if the game style option changed certain values rather than formed its own variable.  Funny though, I've done something wrong.  Now it tells me I have no crews available, even though (in this case) I have four free.  Any idea what I did wrong?  The line now reads

if (((mType > 24 && mType < 32) || mType == 33 || mType == 34 || mType == 35 || mType == 37 || mType == 40) && options.feat_use_endurance != 0) {

![NoCrews](https://user-images.githubusercontent.com/3118014/143792016-cdc26262-7cd2-4a39-b08d-b99bac3760b2.png)

**Comment by rnyoakum** [comment] 2021-11-29 00:37
My first guess would be that you just transferred astronauts to the program this season and they haven't trained, and you have either `game_style 1` or `no_c_training 0` set in the config file. If not, I'd have to see your changed crew.cpp file.

**Comment by rnyoakum** [comment] 2021-11-29 00:57
Also, instead of doing all of the mType checks, couldn't you just use

```
if (IsDuration(mType) && options.feat_use_endurance) {
``` 
or do you intend to exclude `mType == 41`? For quick reference, `IsDuration` is defined in mission_util.cpp.

**Comment by peyre** [comment] 2021-11-29 03:00
D'ohh !  I bet that would be the easy way to do it. 

Oh hell, I did still have game_style 1 set.

**Comment by peyre** [comment] 2021-11-30 03:09
Oh yes, that was it!  I didn't realize they were all new crews.

**Closed** 2021-11-30 03:19 UTC
Labels: Enhancement, Low Priority
