### ISSUE TITLE
Historical lunar landing crash

### ISSUE THREAD

**Issue by willglynn** [raceintospace/raceintospace#40] opened 2012-11-14 05:59 UTC
I get "re-entry corridor" leading to "orbital insertion", followed by another lunar landing sequence, followed by a crash in Launch():

```
for (i = 0; i < 1 + JOINT; i++) {
    /* XXX: was MANNED[i]+1, but why? */
    for (j = 0; j < MANNED[i]; j++) {
        if (MA[i][j].A) {
            if (FINAL >= 100) {
                MA[i][j].A->Mis = 1;    // Successful
            } else if (Data->P[plr].Other & 4) {
                MA[i][j].A->Mis = 2;    // Failure
            }
        }
    }
}
```

Everything seems successful, but it segfaults on the "Failure" branch here with `i` = 0, `j` = 9.

**Comment by rnyoakum** [comment] 2020-10-15 21:08
Reviewing this, I'm pretty sure the problem was [this issue](https://github.com/raceintospace/raceintospace/issues/200).

This issue has two parts:
1. The sudden change in mission step execution, and
2. The segfault caused by the bad `Manned[0]` value

The second part is exactly the problem caused by #200. As for the weird mission ordering, I suspect the pAry overflow is also the issue - after `MANNED[]` it would eventually overflow into STEP. Also possible is that modifying `MANNED[]` created its out-of-range issues that compounded the chaos - such as an `MA[][]` out-of-range access into `Mev`.

Until someone else can reproduce the problem, I'm closing this.

**Closed by rnyoakum** 2020-10-15 21:08 UTC
Labels: bug

**Comment by peyre** [comment] 2020-10-15 21:55
Ryan, thank you!  I love that you've managed to close one of our old Issues.  I'd sure like to clear some of those out.
