### ISSUE TITLE
Missions that fly two capsules should raise your capsule's Safety by 2 points

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#328] opened 2020-03-06 17:58 UTC
The Manned Orbiting Lab is different from the historical proposal; its flight profile is more like Soyuz 4/5.  That is, it's two capsules (or shuttles) launching separately and docking in orbit and conducting a couple duration steps.  I flew it once hoping to gain +2 Safety to my capsule, but since both launches were of the same capsule, it only got +1 Safety.  This was frustrating because I was flying effectively two capsule missions in one - and risking lives and capsules twice.  Seems to me that on missions like that you should get +1 for each capsule that's flying.

This should probably also apply to the Joint Manned Orbital**s** Docking missions, for the same reason.

**Comment by peyre** [comment] 2020-03-13 19:24
I just tested the Joint Manned Orbitals Docking mission and confirmed that it, too, only gives 1% Safety (if you're flying two of the same capsule).

**Comment by rnyoakum** [comment] 2020-08-07 19:32
Quick question about this - can you have two different types of craft fly a joint mission, or do they have to be the same program?

**Comment by peyre** [comment] 2020-08-07 19:57
That's a good question.  You, you can use two different craft on one of these--I've done it with the MOL--and if so, each capsule gets a point of Safety.  So if you fly a Gemini and an Apollo, each will go up one point - but if you fly two Apollos, your Apollo capsule only gets 1 point.

**Comment by rnyoakum** [comment] 2020-08-07 20:42
I'm also guessing that if you use two rockets of the same type on a joint mission, you only get +1 Safety whereas two different types (say, an Atlas w/ DM on rendezvous with a Titan/Gemini) would each get +1 Safety.

Looking over it, this appears to be pretty straightforward. MissionSetDown() is called after the mission, and it updates the hardware safety, damage, steps, fail count, etc. The function advances through the mission hardware array, updating each component that was used one by one. When it modifies a hardware component, it resets the component's MisSucc & MisFail fields - they're meant for temporary use in the mission. Thus, when the loop encounters the next reference to the component (in the second launch) the MisSucc & MisFail fields are already 0, as if the component was never used. Thinking the component was never tested, it awards no additional Safety point.

**Comment by peyre** [comment] 2020-08-07 20:47
That sounds about right; I figured it was something along those lines.  Yes, I expect the same would hold for rockets, though that's less important since the relevant rockets are likely to be near Max Safety by the time you're flying these missions.

**Comment by rnyoakum** [comment] 2020-09-17 00:40
I was looking at this when I realized a problem - the game currently doesn't differentiate between the successes/failures of different instances of the components. For example, a rocket is supposed to gain a point of safety if it was used successfully, and not if it blew up on the pad. But in the case of a joint launch, there may be one rocket that fires successfully, and the other that blows up on the pad (but not catastrophically). Logically, the rocket should gain +1 safety: +1 for the successful launch, and nothing for the failed launch. It would be erroneous to look at the mission, see that there was a successful rocket test and then assign +2 (+1 for each rocket).

This makes the issue much, much more complicated because it involves rewriting how the game evaluates component success.

**Comment by hweimer** [comment] 2021-05-01 20:08
This could be achieved relatively easily by making the MisSucc and MisFail fields in the Equipment struct to be arrays of length 2 and handling the success and failure information on a pad by pad basis. (The MissionSetDown function loops over both pads, so it follows this logic already). The downside of this approach is that it would break save game compatibility before #478 is merged.

**Comment by peyre** [comment] 2021-05-05 15:46
If you mean it would break save games, I don't really see a problem.  We're going from version 1.1 to 2.0, so some incompatibility with earlier saves can reasonably be expected by users.

**Comment by hweimer** [comment] 2021-05-05 18:02
Still, I don't think such a minor issue would justify breaking backwards compatibility. I'd rather defer the break to when #440 is resolved and ditch the old format completely (or at least do not allow to load PBEM games in the legacy format).

**Comment by hweimer** [comment] 2023-03-31 16:43
Oh, I see what the problem is. The historical model never got moved to a JSON file, which results in a misaligned Data struct. Should not be too hard to fix. The basic model should work, though.

**Closed** 2023-03-31 22:47 UTC
Labels: Enhancement, Low Priority

**Comment by peyre** [comment] 2023-03-31 23:35
Thanks, that seems to have fixed it.

**Comment by peyre** [comment] 2023-04-01 18:48
Just tested it.  I flew the MOL with my Apollo capsule at 92%, and after the successful mission it had raised to 94%, so confirmed.
