### ISSUE TITLE
Game locked up during a mission

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#721] opened 2022-11-24 18:47 UTC
I just flew a Jt. Lunar Orbital LM Test EOR.  The mission flew successfully, but on the Recovery/Landing step the game locked up hard.  No error showed in the terminal window.  I couldn't X out, and had to Kill the process--Stop and End didn't close it.

![Locked up](https://user-images.githubusercontent.com/3118014/203849657-cbb9d23c-434a-4b90-b384-0160eb2ccac2.png)

**Comment by peyre** [comment] 2022-11-24 18:51
I loaded the autosave, then flew the same mission again.  This time it had a (noncatastrophic?) failure on the LEM Thrust Test step, and the game locked up again, like before.

**Comment by hweimer** [comment] 2022-11-25 17:16
Can you attach the autosave to this issue (might need to gzip it first) or send it to me by e-mail?

**Comment by peyre** [comment] 2022-11-25 17:46
Oh right.  Here you go!

    On Friday, November 25, 2022 at 09:16:18 AM PST, Hendrik W. ***@***.***> wrote:  
 
 


Can you attach the autosave to this issue (might need to gzip it first) or send it to me by e-mail?

**Comment by peyre** [comment] 2022-11-25 17:46
I've emailed it to you.

**Comment by hweimer** [comment] 2022-11-25 21:37
This is a regression caused by #717. For some reason, the docking step is not carried out (you go directly from earth orbital activities to TLI), which causes an infinite loop during prestige allocation. Looks like joint docking missions without having a docking module assigned is a problem.

**Comment by peyre** [comment] 2022-11-25 22:20
I never would have guessed!  Is this reasonably fixable?

**Comment by hweimer** [comment] 2022-11-25 22:35
I have fixed the underlying issue (the problem was that the fake DM was not assigned to the first pad), but how did you end up with a docking safety of 84% in that game? Starting from 40% and adding either 5% or 10% should never take you to 84% unless I am missing something.

**Comment by peyre** [comment] 2022-11-25 22:56
That's a good question!  I don't know how it happened.  Maybe something, somewhere is adding the Docking Specialist's DO skill to the DM Safety?

**Closed** 2022-11-25 22:57 UTC
Labels: bug

**Comment by hweimer** [comment] 2022-11-25 23:10
No, it's already in the R&D building that the safety is shown at 84%. The DO skill isn't added at all because it appears that the first (unmanned) pad is in charge when it comes to docking steps.

**Comment by rnyoakum** [comment] 2022-11-26 02:05
I'd have to check if the news items are allowed to affect the DM, but could one of them have added to/subtracted from the program R&D?

**Comment by peyre** [comment] 2022-11-26 03:46
I don't see anything like that in the Viewing Stand.  About the closest I can find is the announcement that the Max Safety of probes will be raised 5%.

**Comment by peyre** [comment] 2022-11-26 03:59
Not that I could tell.

    On Friday, November 25, 2022 at 06:05:37 PM PST, Ryan Yoakum ***@***.***> wrote:  
 
 


I'd have to check if the news items are allowed to affect the DM, but could one of them have added to/subtracted from the program R&D?
