### ISSUE TITLE
Launch abort teleports capsule into space

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#530] opened 2021-04-18 20:20 UTC
I had a last-second abort on the launch, but instead of canceling, or even attempting launch again, the mission went straight to orbital insertion burn.

![Boosters 1](https://user-images.githubusercontent.com/3118014/115159576-b1711600-a048-11eb-96d2-c260bcfc8678.png)
![Boosters 2](https://user-images.githubusercontent.com/3118014/115159578-b2a24300-a048-11eb-85ab-d43a8ca88ea3.png)

**Comment by hweimer** [comment] 2021-04-19 21:12
That's a type 7 failure, which damages the equipment permanently but lets the mission continue normally. I think this was meant to be a different case than type 24, which additionally ends the mission but that one says "hardware recovered" in the comment. However, hardware recovery has never been implemented AFAICS.

**Comment by peyre** [comment] 2021-04-19 21:49
Maybe this was intended for minishuttles, since they're reusable.  In Liftoff you pay 2MB per launch to refurbish the shuttle, so maybe this mechanic was meant to replace that by damaging reusable stuff that suffered certain types of failure.  And, like deleting them when they're supposed to have been destroyed, it was never implemented.  Just a guess.

**Comment by rnyoakum** [comment] 2021-04-29 20:38
> That's a type 7 failure, which damages the equipment permanently but lets the mission continue normally.I think this was meant to be a different case than type 24, which additionally ends the mission but that one says "hardware recovered" in the comment. However, hardware recovery has never been implemented AFAICS.

I checked my notes, and Type 7 failures have _a lot_ of issues going on. I'll address some of them in a later post.

I propose that the problem is that the launch error is classified as a type 7 error. Examining the cases, type 7 errors are possible for 6 different steps:
- F100: Minishuttle launch error
- F304: Minishuttle landing error (3 instances)
- F007: Orbital EVA error
- F107: Orbital EVA error (Mercury/Vostok)
- F015: Lunar EVA error
- F115: Lunar EVA (Cricket / LK)

Notably, for five of the six steps - excepting F100 - there is no difference in how the mission proceeds between success and failure. For an EVA error, absent death the EVA ends and the mission advances to the next step; regardless of success, there's not much to do but continue.* Same with the Minishuttle landing: bumpy landing or no, the craft is on the ground. Whether the mission continues or branches to the failure step is academic, though I argue it should branch to failure (that's what the StepInfo value suggests). The Minishuttle launch error is different; it matters very much whether the step succeeds. As hweimer suggested, the Minishuttle launch failure has far more in common with a type 24 error than with a type 7 error. He also notes that the type 24 error says "hardware recovered" in a comment in the code, which also seems fitting for this error. Per the text, there is a last second countdown abort - the mission should end, and the hardware **should be** recovered.

I suggest reclassifying it as a type 24 error. There are a few other changes we should probably make to the fails.cdr file at the same time.


*_An EVA failure in an exceptional situation - when the crew has to do an emergency spacewalk back from a disabled LM to the capsule - is an odd case and I'm not sure the game handles it properly. I don't remember the details at this time._

**Comment by peyre** [comment] 2021-04-29 20:49
_Ooh_, sounds messy.  Leave it to RIS to have a very convoluted issue cause a very simple-looking anomaly.

**Comment by hweimer** [comment] 2021-04-29 22:24
Hmm, I'm not sure that "hardware recovered" would be fitting here, as a major fuel leak in the boosters sounds like you should not be able to use the rocket again. The commit referenced in the PR fixes the bug by having code 7 failures on launch terminating the mission, the same way as it is currently done with code 16 and 17 failures.

**Comment by rnyoakum** [comment] 2021-04-29 23:56
> Hmm, I'm not sure that "hardware recovered" would be fitting here, as a major fuel leak in the boosters sounds like you should not be able to use the rocket again. The commit referenced in the PR fixes the bug by having code 7 failures on launch terminating the mission, the same way as it is currently done with code 16 and 17 failures.

But you would be able to reuse the capsule, LM, etc. I saw your proposed solution, and I think part of the problem is that code 7 failures have **many** flaws; the different cases shouldn't be handled the same way. I'm writing up a new issue discussing those problems. I don't think the right solution is to build in a special case inside of the code. I think moving it to a code 24 is the right call, but if not a code 24 than I'd suggest creating a new code.

**Comment by hweimer** [comment] 2021-04-30 06:34
All right, let's make this a code 24 then.

**Closed** 2021-04-30 21:38 UTC
Labels: bug
