### ISSUE TITLE
Primary crew not replaced like it should be

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#325] opened 2020-02-21 18:03 UTC
I just got the following newscast saying the primary crew will be replaced with the backup crew, but the primary crew is still in line to fly the mission.  I have a save in case it's needed or helpful.  (I think this might be one we had thought we'd fixed already, but maybe the fix didn't do it.)

![Common Cold](https://user-images.githubusercontent.com/3118014/75059203-51590100-5491-11ea-815c-5011bce7d0ac.png)
![Both Crews](https://user-images.githubusercontent.com/3118014/75059208-53bb5b00-5491-11ea-85a1-1e94f6456ced.png)

**Comment by peyre** [comment] 2020-02-23 19:29
Hang on, this might be a duplicate of #286.

**Comment by peyre** [comment] 2020-03-03 05:22
Well either way it's still happening.  I just got it playing as the Soviets.

![Primary crew caught cold](https://user-images.githubusercontent.com/3118014/75745353-ed71dc00-5ccb-11ea-85d2-04f6e1804e1e.png)
![Primary crew has (not) caught cold](https://user-images.githubusercontent.com/3118014/75745354-ee0a7280-5ccb-11ea-989c-8a30e1ba48a9.png)

**Comment by rnyoakum** [comment] 2020-03-18 20:33
This is a duplicate of issue #286, so I'm closing this issue.

**Closed by rnyoakum** 2020-03-18 20:33 UTC
Labels: bug
